import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from '@/context/Auth'
import { Toaster } from '@/components/ui/sonner'
import Provider from '@/utils/Provider'
const inter = Inter({ subsets: ['latin'] })
import { Analytics } from '@vercel/analytics/react'
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <AuthProvider>{children}</AuthProvider>
        </Provider>
        <Analytics />
        <Toaster />
      </body>
    </html>
  )
}
